separate the game code in the backend
maresverbrugge/Transcendence pull request #10
Opened 2024-10-08 16:35 UTC by Jeroenvh99

2024-10-08 16:48 UTC, fhuisman commented on backend/Dockerfile
> +RUN npm install axios
axios package toevoegen aan package.json, dan installeerd RUN npm install alle packages, ook axios.

2024-10-08 16:52 UTC, fhuisman commented on backend/src/app.controller.ts
> +	this.appService.getGame();
getHello is een voorbeeld functie van NestJS. die gaan we uiteindelijk niet gebruiken. deze code mag ook worden verplaatst binnen het 'game' mapje. in een game.gateway.ts file (als je t via websockets wil doen en niet via http)

2024-10-08 17:02 UTC, fhuisman requested changes
Hey jeroen, 
Het is ook de bedoeling dat de app.service app.module en app.controller vrij blijven van 'game' code. Dat was misschien niet heel duidelijk. De. game code mag allemaal naar files in het 'game' mapje. Ik denk ook niet dat game een module moet worden, maar een gateway en service.
In service staat altijd echt de functies die dingen uitvoeren.
Gateway gaat over websockets, dat als er een bepaalde message binnenkomt via websockets, dat de juiste functie uit de service wordt aangeroepen.
Met module kun je een module (soort class) maken in een ander deel van je code door de constructor te callen, en dan kun je losse functies uit de module gebruiken, dat gebruiken we bijvoorbeeld voor Prisma, want ik wil bijv. in mijn deel van de code prisma.channel.create() gebruiken, en Mares in haar gedeelte prisma.user.create(). Ik denk dat dat voor de game niet nodig is.

2024-10-14 16:36 UTC, Jeroenvh99 commented on backend/Dockerfile
> +RUN npm install axios
Gedaan

2024-10-15 15:22 UTC, maresverbrugge approved these changes
We restructured the code with the 3 of us, Flen, Jeroen and me (the Mrazzle). We tested it and it seems to work fine. Whoo, on to the next step!

2024-10-15 17:32 UTC, fhuisman commented on backend/src/game/game.module.ts
> +export class GameModule {
Ja, beter

2024-10-15 17:32 UTC, fhuisman commented on backend/src/app.controller.ts
> +	this.appService.getGame();
kan er voor nu nog blijven staan

2024-10-15 17:33 UTC, fhuisman commented
Yes, this way it can be merged with the main :)

2024-10-15 17:35 UTC, fhuisman approved these changes

2024-10-15 17:35 UTC, merged