Integrate the game so far
maresverbrugge/Transcendence pull request #21
Opened 2024-12-06 15:26 UTC by Jeroenvh99

2024-12-06 18:42 UTC, fkoolhoven reviewed
Heel fijn Jeroen! Deze PR zag er een stuk overzichtelijker uit dus dat was fijn reviewen :) Ik hoop dat je wat aan mijn comments hebt. Laat het weten als je ergens niet uit komt! Van gateways en websockets heb ik zelf niet zo veel verstand dus misschien dat Flen daar nog even naar kan kijken.

2024-12-06 18:42 UTC, fkoolhoven commented on frontend/src/App.tsx
> +import Game from './pages/game.tsx';
Beetje nitpicky dit maar een style dingetje: Het is denk ik mooi als alle files een capitalized naam hebben. Dus Game ipv game. Dan past het bij hoe de files in main er nu uit zien.

2024-12-06 18:42 UTC, fkoolhoven commented on backend/src/game/game.controller.ts
> +    }
De logica hier hoort eigenlijk in de service, niet in de controller. Neem anders even een kijkje in main hoe de andere Controllers er uit zien.

2024-12-06 18:42 UTC, fkoolhoven commented on backend/src/game/game.service.spec.ts
Gebruik je deze tests? Anders kan je de spec.ts files ook verwijderen wat mij betreft.

2024-12-06 18:42 UTC, fkoolhoven commented on frontend/src/pages/game.tsx
> +        });
Volgens mij heet de token 'authenticationToken' in localstorage, niet 'token', of is dit iets anders?

2024-12-06 18:42 UTC, fkoolhoven commented on backend/src/game/game.controller.spec.ts
Gebruik je deze file?

2024-12-07 12:26 UTC, fhuisman commented on backend/src/game/game.gateway.ts
> +			game: newGame,
Als je niet het hele object 'game' meestuurt over de websocket, maar alleen aan de frontend laat weten dat er een nieuwe game is (je zou bijvoorbeeld alleen ('newGame', game.ID) kunnen sturen). En dat de frontend daarna een GET request maakt voor de nieuwe game. Dan kan je beter beveiligen dat de juiste persoon alleen toegang heeft tot deze data, want de GET request kan je met de token beveiligen.. Ik probeer dat nu ook te implementeren in mijn code en vind dat eigenlijk wel een hele elegante manier. Het is iets meer werk, maar wel heel secure en ook overzichtelijk en makkelijk als je nog meer code gaat schrijven (scalable)

2024-12-07 12:55 UTC, maresverbrugge reviewed
Ziet er goed uit, wordt denk ik steeds overzichtelijker wat in welke file hoort.
Extra opmerking aan de hand van wat er in whatsapp is besproken, dit geld voor iedereen, zeker nu we onze deadline zo erg aan het naderen zijn: probeer de prioriteiten op volgorde te zetten van wat echt moet functioneren, en dan later vanaf die versie nieuwe dingen extra toe te voegen.

2024-12-07 12:55 UTC, maresverbrugge commented on backend/src/prisma/schema.prisma
> +  spectators        User[]        @relation("watched")
Ik ben niet zo'n gamer dus misschien mis ik iets, maar wat zijn "spectators" en waarvoor worden die gebruikt

2024-12-07 13:14 UTC, fhuisman commented on backend/src/game/game.gateway.ts
> +	async handleNewGameAccept(client: any, gameID: string, socketID: string) {
Deze logica kan ook gedaan worden met een POST request (bijvoorbeeld POST http://localhost/game/acceptGame/:gameID/:token). 
Je gebruikt hier niet de websocket om in real time iets bij een andere user te updaten. Dus dan zou ik het altijd via een POST request doen. 
Is discutabel, want zo werkt het ook. Het is denk ik gewoon mooiere code als je HTTP request gebruikt waar kan.

2024-12-07 13:16 UTC, fhuisman commented on backend/src/game/game.gateway.ts
Alle logica hoort in de game.service.ts file, net als bij een controller. Dat je na een @subscribemessage een functie uit je service called om het te handelen.

2024-12-07 13:18 UTC, fhuisman commented on backend/src/game/game.service.ts
> +			where: { matchID: gameID },
voor readability zou ik game en match niet door elkaar gebruiken. Overal match en matchID etc gebruiken.

2024-12-07 13:32 UTC, fhuisman commented on frontend/src/components/Game/GameControl.tsx
Kan je een keer uitleggen hoe de logic van de game werkt, ben ik heel benieuwd naar!
Wordt de positie van de bal in de backend bijgehouden?
of word er alleen doorgegeven als de richting en snelheid veranderd?
Kan er dan bij een trage verbinding bij een vd twee spelers een verschil tussen de twee frontends ontstaan?

2024-12-07 13:37 UTC, fhuisman commented on frontend/src/pages/game.tsx
> +		socketIo.on('newGame', (data: any) => {
kijk, dan kan je hier on('newGame', () => fetchGames() callen en dan is het veel overzichtelijker (zie mijn comment in de game.gateway.ts (line 50))

2024-12-07 13:37 UTC, fhuisman commented on frontend/src/pages/game.tsx
> +		socket.emit('acceptGame', gameID, socket.id);
dit kan denk ik met een post request

2024-12-07 13:37 UTC, fhuisman commented on frontend/src/pages/game.tsx
> +		socket.emit('createNewGame', socket.id);
dit kan denk ik ook met een POST request

2024-12-07 13:41 UTC, fhuisman requested changes
Hey Jeroen!
Ik heb wat op- en aanmerkingen geschreven en dat zijn vooral stijlkeuzes. De code werkt op deze manier maar ik denk dat het mooiere en betere code kan worden!

2025-01-04 14:46 UTC, closed without merging